version: '3.3'

services:
  redis:
    env_file: .env
    image: redis:7.0-rc-alpine
    container_name: "redis"
    command: "redis-server /usr/local/etc/redis --requirepass ${REDIS__PASSWORD}"
    ports:
      - "6379"
    restart: "unless-stopped"
    networks:
      - botnet
  database:
    env_file: .env
    image: "postgres:14.2-alpine"
    container_name: "db"
    volumes:
      - "./pg/data:/var/lib/postgresql/data"
      - "./pg/init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: $POSTGRES__LOGIN
      POSTGRES_PASSWORD: $POSTGRES__PASSWORD
      POSTGRES_DB: $POSTGRES__DB
    ports:
      - "5432"
    restart: unless-stopped
    networks:
      - botnet
  db_migration:
    env_file: .env
    container_name: "migr"
    restart: "on-failure"
    command: sh -c "python -m alembic upgrade head"
    depends_on:
      - database
    networks:
      - botnet

networks:
  botnet:
    driver: bridge