version: '3.3'

services:
  bot:
    env_file: .env
    container_name: "eiee-bot"
    build:
      context: .
    working_dir: "/usr/src/app/eiee-bot"
    volumes:
      - .:/usr/src/app/eiee-bot
    command: python -m app
    ports:
      - "5500:5500"
    restart: unless-stopped
    networks:
      - botnet
  redis:
    env_file: .env
    image: redis:7.0-rc-alpine
    container_name: "eiee-redis"
    volumes:
      - "./redis.conf:/usr/local/etc/redis"
      - "./redis/data:/data"
    command: "redis-server /usr/local/etc/redis --requirepass ${REDIS__PASSWORD}"
    ports:
      - "6379"
    restart: "unless-stopped"
    networks:
      - botnet
  database:
    env_file: .env
    image: "postgres:14.2-alpine"
    container_name: "eiee-db"
    volumes:
      - "./pg/data:/var/lib/postgresql/data"
      - "./pg/init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: $POSTGRES__LOGIN
      POSTGRES_PASSWORD: $POSTGRES__PASSWORD
      POSTGRES_DB: $POSTGRES__DB
    ports:
      - "5432"
    restart: unless-stopped
    networks:
      - botnet
  db_migration:
    build:
      context: .
    env_file: .env
    container_name: "eiee-migr"
    working_dir: "/usr/src/app/eiee-bot"
    volumes:
      - ./alembic.ini:/usr/src/app/eiee-bot
      - ./alembic:/usr/src/app/eiee-bot
    restart: "on-failure"
    command: sh -c "python -m alembic upgrade head"
    depends_on:
      - database
    networks:
      - botnet
  worker:
    env_file: .env
    container_name: "eiee-worker"
    build:
      context: .
    working_dir: "/usr/src/app/eiee-bot"
    volumes:
      - .:/usr/src/app/eiee-bot
    command: python -m worker
    restart: unless-stopped
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
