"""change field tel

Revision ID: 0002
Revises: 0001
Create Date: 2022-06-01 19:16:26.546457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'tel',
               existing_type=sa.BigInteger(),
               nullable=True)
    op.alter_column('teachers', 'tel',
               existing_type=sa.BigInteger(),
               nullable=True)
    op.alter_column('students', 'tel',
               existing_type=sa.BigInteger(),
               nullable=True)
    op.alter_column('parents', 'tel',
               existing_type=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'tel',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'tel',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('students', 'tel',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('parents', 'tel',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###
