"""delete field full_name

Revision ID: 0003
Revises: 0002
Create Date: 2022-06-02 21:18:52.035161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('parents', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('parents', sa.Column('patronymic', sa.String(), nullable=False))
    op.drop_column('parents', 'full_name')
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('patronymic', sa.String(), nullable=False))
    op.drop_column('students', 'full_name')
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('patronymic', sa.String(), nullable=False))
    op.drop_column('teachers', 'full_name')
    op.add_column('administrators', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('patronymic', sa.String(), nullable=False))
    op.drop_column('administrators', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'patronymic')
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'patronymic')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.add_column('parents', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parents', 'patronymic')
    op.drop_column('parents', 'last_name')
    op.drop_column('parents', 'first_name')
    op.add_column('administrators', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('administrators', 'patronymic')
    op.drop_column('administrators', 'last_name')
    op.drop_column('administrators', 'first_name')
    # ### end Alembic commands ###
