"""delete condition nullable

Revision ID: 0004
Revises: 0003
Create Date: 2022-06-02 21:24:15.930702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'first_name', nullable=True)
    op.alter_column('administrators', 'last_name', nullable=True)
    op.alter_column('administrators', 'patronymic', nullable=True)
    op.alter_column('parents', 'first_name', nullable=True)
    op.alter_column('parents', 'last_name', nullable=True)
    op.alter_column('parents', 'patronymic', nullable=True)
    op.alter_column('students', 'first_name', nullable=True)
    op.alter_column('students', 'last_name', nullable=True)
    op.alter_column('students', 'patronymic', nullable=True)
    op.alter_column('teachers', 'first_name', nullable=True)
    op.alter_column('teachers', 'last_name', nullable=True)
    op.alter_column('teachers', 'patronymic', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'patronymic')
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'patronymic')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.add_column('parents', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parents', 'patronymic')
    op.drop_column('parents', 'last_name')
    op.drop_column('parents', 'first_name')
    op.add_column('administrators', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('administrators', 'patronymic')
    op.drop_column('administrators', 'last_name')
    op.drop_column('administrators', 'first_name')
    # ### end Alembic commands ###
