"""delete condition nullable admin_id field

Revision ID: 0005
Revises: 0004
Create Date: 2022-06-05 16:14:26.900646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('students', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
