"""add new field: telegram_id

Revision ID: 0007
Revises: 0006
Create Date: 2022-06-17 15:40:06.851826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'administrators', ['tel'])
    op.create_unique_constraint(None, 'administrators', ['telegram_id'])
    op.add_column('parents', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'parents', ['tel'])
    op.create_unique_constraint(None, 'parents', ['telegram_id'])
    op.add_column('students', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'students', ['telegram_id'])
    op.create_unique_constraint(None, 'students', ['tel'])
    op.add_column('teachers', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['tel'])
    op.create_unique_constraint(None, 'teachers', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'telegram_id')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'telegram_id')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'telegram_id')
    op.drop_constraint(None, 'administrators', type_='unique')
    op.drop_constraint(None, 'administrators', type_='unique')
    op.drop_column('administrators', 'telegram_id')
    # ### end Alembic commands ###
