"""add field lesson_number

Revision ID: 0009
Revises: 0008
Create Date: 2022-06-19 21:47:32.581211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_tasks', sa.Column('lesson_number', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_tasks', 'lesson_number')
    # ### end Alembic commands ###
