"""change field lesson_number

Revision ID: 0011
Revises: 0010
Create Date: 2022-06-19 21:50:52.256042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_tasks', sa.Column('number', sa.Numeric(), nullable=False))
    op.drop_column('home_tasks', 'home_task_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_tasks', sa.Column('home_task_number', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('home_tasks', 'number')
    # ### end Alembic commands ###
