"""delete access fields from home task

Revision ID: 0012
Revises: 0011
Create Date: 2022-06-19 22:30:42.441148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_tasks', 'access_start')
    op.drop_column('home_tasks', 'access_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_tasks', sa.Column('access_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('home_tasks', sa.Column('access_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
