"""add fields file type

Revision ID: 0013
Revises: 0012
Create Date: 2022-06-20 22:28:18.519135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_task_files', sa.Column('type', sa.String(), nullable=True))
    op.add_column('home_work_files', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_work_files', 'type')
    op.drop_column('home_task_files', 'type')
    # ### end Alembic commands ###
