"""add condition on_delete

Revision ID: 0015
Revises: 0014
Create Date: 2022-06-26 15:58:31.452346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('home_task_files_home_task_id_fkey', 'home_task_files', type_='foreignkey')
    op.create_foreign_key(None, 'home_task_files', 'home_tasks', ['home_task_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('home_work_files_home_work_id_fkey', 'home_work_files', type_='foreignkey')
    op.create_foreign_key(None, 'home_work_files', 'home_works', ['home_work_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('home_works_home_task_id_fkey', 'home_works', type_='foreignkey')
    op.create_foreign_key(None, 'home_works', 'home_tasks', ['home_task_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_works', type_='foreignkey')
    op.create_foreign_key('home_works_home_task_id_fkey', 'home_works', 'home_tasks', ['home_task_id'], ['uuid'])
    op.drop_constraint(None, 'home_work_files', type_='foreignkey')
    op.create_foreign_key('home_work_files_home_work_id_fkey', 'home_work_files', 'home_works', ['home_work_id'], ['uuid'])
    op.drop_constraint(None, 'home_task_files', type_='foreignkey')
    op.create_foreign_key('home_task_files_home_task_id_fkey', 'home_task_files', 'home_tasks', ['home_task_id'], ['uuid'])
    # ### end Alembic commands ###
