"""edit field number int-string

Revision ID: 0016
Revises: 0015
Create Date: 2022-06-30 13:56:01.642939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("home_tasks", "number", existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("home_tasks", "number", existing_type=sa.Numeric())
    # ### end Alembic commands ###
