"""edit field number int-string

Revision ID: 0017
Revises: 0016
Create Date: 2022-06-30 17:52:05.851103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("home_tasks", "number", type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("home_tasks", "number", type_=sa.Numeric())
    # ### end Alembic commands ###
