"""remove some fields

Revision ID: 0019
Revises: 0018
Create Date: 2022-07-04 14:39:26.011194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "access_end")
    op.drop_column("groups", "access_start")
    op.drop_constraint("parents_telegram_id_key", "parents", type_="unique")
    op.drop_column("parents", "telegram_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parents", sa.Column("telegram_id", sa.BIGINT(), autoincrement=False))
    op.create_unique_constraint("parents_telegram_id_key", "parents", ["telegram_id"])
    op.add_column(
        "groups", sa.Column("access_start", postgresql.TIMESTAMP(), autoincrement=False)
    )
    op.add_column(
        "groups", sa.Column("access_end", postgresql.TIMESTAMP(), autoincrement=False)
    )
    # ### end Alembic commands ###
