"""add new table

Revision ID: 0020
Revises: 0019
Create Date: 2022-07-05 17:11:44.901074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0020"
down_revision = "0019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unregistered_users",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("tel", sa.BigInteger(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("tel"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unregistered_users")
    # ### end Alembic commands ###
