"""change condition nullable

Revision ID: 0021
Revises: 0020
Create Date: 2022-07-05 17:21:36.700482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unregistered_users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unregistered_users', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
