"""add condition ondelete in section

Revision ID: 0024
Revises: 0023
Create Date: 2022-07-05 19:16:00.201036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0024'
down_revision = '0023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sections_group_id_fkey', 'sections', type_='foreignkey')
    op.drop_constraint('sections_student_id_fkey', 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sections', 'groups', ['group_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key('sections_student_id_fkey', 'sections', 'students', ['student_id'], ['id'])
    op.create_foreign_key('sections_group_id_fkey', 'sections', 'groups', ['group_id'], ['uuid'])
    # ### end Alembic commands ###
