"""add conditions ondelete

Revision ID: 0025
Revises: 0024
Create Date: 2022-07-05 19:17:09.759575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('home_tasks_group_id_fkey', 'home_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'home_tasks', 'groups', ['group_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('home_works_student_id_fkey', 'home_works', type_='foreignkey')
    op.create_foreign_key(None, 'home_works', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_works', type_='foreignkey')
    op.create_foreign_key('home_works_student_id_fkey', 'home_works', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'home_tasks', type_='foreignkey')
    op.create_foreign_key('home_tasks_group_id_fkey', 'home_tasks', 'groups', ['group_id'], ['uuid'])
    # ### end Alembic commands ###
