"""delete condition nullable from students

Revision ID: 0026
Revises: 0025
Create Date: 2022-07-05 19:22:40.009339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0026'
down_revision = '0025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
