"""add condition on delete set 0

Revision ID: 0030
Revises: 0029
Create Date: 2022-07-07 01:53:00.598888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0030'
down_revision = '0029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
