"""change field in group

Revision ID: 0032
Revises: 0031
Create Date: 2022-07-12 21:45:12.250066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0032'
down_revision = '0031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('groups_teacher_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'teachers', ['teacher_id'], ['id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_teacher_id_fkey', 'groups', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('groups', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
