"""create table rejected files

Revision ID: 0034
Revises: 0034
Create Date: 2022-07-19 01:09:00.146832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0034"
down_revision = "0033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rejected_files",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("work_uuid", postgresql.UUID(), nullable=True),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["work_uuid"], ["home_works.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.alter_column(
        "administrators",
        "access_start",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "administrators",
        "access_end",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "students", "access_start", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "students", "access_end", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "teachers", "access_start", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "teachers", "access_end", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teachers", "access_end", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "teachers", "access_start", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "students", "access_end", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "students", "access_start", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "administrators",
        "access_end",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "administrators",
        "access_start",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_table("rejected_files")
    # ### end Alembic commands ###
