"""change field uuid in rejected files

Revision ID: 0036
Revises: 0035
Create Date: 2022-07-19 01:50:58.216591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0036'
down_revision = '0035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rejected_files', sa.Column('id', sa.String(), nullable=False))
    op.drop_column('rejected_files', 'file_id')
    op.drop_column('rejected_files', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rejected_files', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('rejected_files', sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rejected_files', 'id')
    # ### end Alembic commands ###
